### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by junweimoo** [AY2223S1-CS2103T-W16-4/tp#111]

**Comment by Thing1Thing2** [comment]
Hi @junweimoo , just a suggestion... it would be help to understand what changes will be made in this issue by adding a description. Thank you :smile:

**Comment by sikai00** [comment]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/63795894/193991279-f0d8c5bf-cbe4-4dbc-92be-349ad9a5dd71.png">
not particularly sure where in the textbook the exact practice is described, but i think a general guideline is that issues should be well defined

**Comment by sikai00** [comment]
completed with #113
