### ISSUE TITLE
[PE-D][Tester C] Wrong error message

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W16-4/tp#222]
Input wrong prefixes displays `unknown command` error message instead, even though the command word was correct.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: sarrrdin/ped#3

**Comment by Thing1Thing2** [comment]
Follow-up link:
https://github.com/sarrrdin/ped/issues/3#issuecomment-1296464794

![image](https://user-images.githubusercontent.com/93027319/198925002-323b4c88-2d88-4058-a098-53a41c3596be.png)
