### ISSUE TITLE
[PE-D][Tester C] Add phone number cannot add symbols but only numbers

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W16-4/tp#226]
Would it be better to allow users to add phone numbers with symbols? Especially for those of overseas clients?

Furthermore, there cannot be spacings in the numbers too, such as `9783 0909` will fail. Would it be better to allow for spacings?

`addClient n/ dennis p/ +868989898222229`

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: sarrrdin/ped#4

**Comment by ThomasHoooo** [comment]
Feature flaw
