### ISSUE TITLE
[PE-D][Tester C] ListClient filtering issue

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W16-4/tp#251]
Commands such as `listClient b/tomorrow b/week  b/ month` works too and lists out clients who's birthday is tomorrow... maybe can throw error message for commands with so many prefixes?

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: sarrrdin/ped#11

**Comment by rexong** [comment]
I dont think i can reproduce this bug. I tried on my side but it works as intended, ie `listClient b/tomorrow b/week b/ month` will result in `listClient b/month`
