### ISSUE TITLE
[PE-D][Tester C] DeleteMeeting does not delete index despite client added in

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W16-4/tp#258]
![image.png](https://raw.githubusercontent.com/sarrrdin/ped/main/files/11f6b3fc-e2dd-42ac-b235-8e7150d3d2eb.png)

while it seems that `deleteMeeting` deletes by index number of client, the below command fails despite that having one client added in.

![image.png](https://raw.githubusercontent.com/sarrrdin/ped/main/files/4766e76c-cf5c-4779-b78a-bdb880ce4f8b.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: sarrrdin/ped#13

**Comment by rexong** [comment]
I dont think this is an error? the tester tried to delete a meeting using index from the list of client rather than from the list of meeting.

**Comment by sikai00** [comment]
agree with @rexong, likely this is just a misuse of the command.
